version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0.33-debian
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: database_development
    ports:
      - "3306:3306"
